apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: litefunctions-gateway
  namespace: default
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "floatier-finnegan-stumblingly.ngrok-free.dev"
    - "floatier-finnegan-stumblingly.ngrok-free.dev"
    - "git.example.com"
