name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image with Kaniko
      uses: docker://gcr.io/kaniko-project/executor:latest
      with:
        args: --dockerfile=Dockerfile --context=. --no-push --tarPath=/workspace/image.tar
    - name: Push to Gitea Registry
      uses: docker://quay.io/skopeo/stable:latest
      with:
        args: copy --dest-creds ${{ secrets.GITEA_USERNAME }}:${{ secrets.GITEA_PASSWORD }} --dest-tls-verify=false docker-archive:/workspace/image.tar docker://litefunctions-gitea-http:3000/test-repo:latest