name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Kaniko config
        run: |
          mkdir -p $HOME/.docker
          echo '{"auths":{"litefunctions-gitea-http:3000":{"auth":"'$(echo -n ashudev:${{ secrets.GITEA_TOKEN }} | base64)'"}}}' > $HOME/.docker/config.json
          
      - name: Build and Push with Kaniko  
        uses: docker://gcr.io/kaniko-project/executor:latest
        with:
          args: >
            --dockerfile=Dockerfile
            --context=.
            --destination=litefunctions-gitea-http:3000/ashudev/test-repo:latest
            --skip-tls-verify
            --insecure
            --skip-push-permission-check
