// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package adaptors

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProjectRole string

const (
	ProjectRoleOwner   ProjectRole = "owner"
	ProjectRoleManager ProjectRole = "manager"
	ProjectRoleViewer  ProjectRole = "viewer"
)

func (e *ProjectRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectRole(s)
	case string:
		*e = ProjectRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectRole: %T", src)
	}
	return nil
}

type NullProjectRole struct {
	ProjectRole ProjectRole
	Valid       bool // Valid is true if ProjectRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectRole), nil
}

type Credential struct {
	ID              []byte
	UserID          []byte
	PublicKey       []byte
	AttestationType pgtype.Text
	Aaguid          []byte
	SignCount       int64
	Transports      []string
	Flags           int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Endpoint struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Method     string
	Scope      string
	FunctionID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type Function struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Name      string
	Language  string
	Path      string
	CreatedBy []byte
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedBy   []byte
	CreatedAt   pgtype.Timestamptz
}

type ProjectInvite struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	InviteCode string
	CreatedBy  []byte
	ExpiresAt  pgtype.Timestamptz
	UsedAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID          []byte
	Name        string
	DisplayName string
	Icon        pgtype.Text
}

type UserProjectAccess struct {
	ID        pgtype.UUID
	UserID    []byte
	ProjectID pgtype.UUID
	Role      ProjectRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserSession struct {
	SessionID string
	UserID    []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UserAgent pgtype.Text
	IpAddress pgtype.Text
}

type WebauthnSession struct {
	SessionID          string
	UserName           string
	Challenge          []byte
	UserID             []byte
	AllowedCredentials [][]byte
	ExpiresAt          pgtype.Timestamptz
	RpID               pgtype.Text
	CredParams         []byte
	Extensions         []byte
	UserVerification   pgtype.Text
	Mediation          pgtype.Text
}
