// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package adaptors

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (project_id, name, method, scope, function_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, method, scope, function_id, created_at
`

type CreateEndpointParams struct {
	ProjectID  pgtype.UUID
	Name       string
	Method     string
	Scope      string
	FunctionID pgtype.UUID
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.ProjectID,
		arg.Name,
		arg.Method,
		arg.Scope,
		arg.FunctionID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Method,
		&i.Scope,
		&i.FunctionID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints
WHERE id = $1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, id)
	return err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, project_id, name, method, scope, function_id, created_at
FROM endpoints
WHERE id = $1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id pgtype.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Method,
		&i.Scope,
		&i.FunctionID,
		&i.CreatedAt,
	)
	return i, err
}

const listEndpointsForProject = `-- name: ListEndpointsForProject :many
SELECT e.id, e.project_id, e.name, e.method, e.scope, e.function_id, e.created_at, f.name as function_name, f.is_async
FROM endpoints e
JOIN functions f ON e.function_id = f.id
WHERE e.project_id = $1
ORDER BY e.name ASC, e.method ASC
`

type ListEndpointsForProjectRow struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	Name         string
	Method       string
	Scope        string
	FunctionID   pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	FunctionName string
	IsAsync      bool
}

func (q *Queries) ListEndpointsForProject(ctx context.Context, projectID pgtype.UUID) ([]ListEndpointsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listEndpointsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEndpointsForProjectRow
	for rows.Next() {
		var i ListEndpointsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Method,
			&i.Scope,
			&i.FunctionID,
			&i.CreatedAt,
			&i.FunctionName,
			&i.IsAsync,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointsSearch = `-- name: ListEndpointsSearch :many
SELECT e.id, e.project_id, e.name, e.method, e.scope, e.function_id, e.created_at, f.name as function_name, f.is_async
FROM endpoints e
JOIN functions f ON e.function_id = f.id
WHERE e.project_id = $1
  AND (
        $2::text = '' OR
        e.name ILIKE '%' || $2::text || '%'
      )
ORDER BY e.name ASC, e.method ASC
LIMIT $3 OFFSET $4
`

type ListEndpointsSearchParams struct {
	ProjectID pgtype.UUID
	Column2   string
	Limit     int32
	Offset    int32
}

type ListEndpointsSearchRow struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	Name         string
	Method       string
	Scope        string
	FunctionID   pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	FunctionName string
	IsAsync      bool
}

func (q *Queries) ListEndpointsSearch(ctx context.Context, arg ListEndpointsSearchParams) ([]ListEndpointsSearchRow, error) {
	rows, err := q.db.Query(ctx, listEndpointsSearch,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEndpointsSearchRow
	for rows.Next() {
		var i ListEndpointsSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Method,
			&i.Scope,
			&i.FunctionID,
			&i.CreatedAt,
			&i.FunctionName,
			&i.IsAsync,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
SET name = $2, method = $3, scope = $4, function_id = $5
WHERE id = $1
RETURNING id, project_id, name, method, scope, function_id, created_at
`

type UpdateEndpointParams struct {
	ID         pgtype.UUID
	Name       string
	Method     string
	Scope      string
	FunctionID pgtype.UUID
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.ID,
		arg.Name,
		arg.Method,
		arg.Scope,
		arg.FunctionID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Method,
		&i.Scope,
		&i.FunctionID,
		&i.CreatedAt,
	)
	return i, err
}

const updateEndpointMethodScope = `-- name: UpdateEndpointMethodScope :one
UPDATE endpoints
SET method = $2, scope = $3
WHERE id = $1
RETURNING id, project_id, name, method, scope, function_id, created_at
`

type UpdateEndpointMethodScopeParams struct {
	ID     pgtype.UUID
	Method string
	Scope  string
}

func (q *Queries) UpdateEndpointMethodScope(ctx context.Context, arg UpdateEndpointMethodScopeParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpointMethodScope, arg.ID, arg.Method, arg.Scope)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Method,
		&i.Scope,
		&i.FunctionID,
		&i.CreatedAt,
	)
	return i, err
}
